services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app:cached
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8501:8501"
    command: bash -c "streamlit run streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0"

  airflow:
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - db
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=50000
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AIRFLOW_USER=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_FIRSTNAME=${AIRFLOW_FIRSTNAME}
      - AIRFLOW_LASTNAME=${AIRFLOW_LASTNAME}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts/airflow_create_user.sh:/opt/airflow/scripts/airflow_create_user.sh:ro
    command: ["bash","-c","/opt/airflow/scripts/airflow_create_user.sh"]

  pgadmin:
    image: dpage/pgadmin4:7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
