-- Generated staging DDL
-- source: data/schemas/staged_schemas_by_season.json
-- generated_at: 

-- DDL for table: stats_defense
DROP TABLE IF EXISTS "stg_stats_defense" CASCADE;
CREATE TABLE "stg_stats_defense" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "tackles" DECIMAL(10,2),
  "tackles_won" DECIMAL(10,2),
  "tackles_def_third" DECIMAL(10,2),
  "tackles_mid_third" DECIMAL(10,2),
  "tackles_att_third" DECIMAL(10,2),
  "tackle_attempts" DECIMAL(10,2),
  "tackle_pct" DECIMAL(10,2),
  "tackles_lost" DECIMAL(10,2),
  "blocks" DECIMAL(10,2),
  "blocked_shots" DECIMAL(10,2),
  "blocked_passes" DECIMAL(10,2),
  "interceptions" DECIMAL(10,2),
  "tackles_plus_interceptions" DECIMAL(10,2),
  "clearances" DECIMAL(10,2),
  "errors" DECIMAL(10,2),
  "touches_def_third" DECIMAL(10,2),
  "touches_mid_third" DECIMAL(10,2),
  "touches_att_third" DECIMAL(10,2),
  "passes_attempted" DECIMAL(10,2),
  "aerials_lost" DECIMAL(10,2),
  "passes_blocks" DECIMAL(10,2),
  "shot_creating_actions_shot" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_gca
DROP TABLE IF EXISTS "stg_stats_gca" CASCADE;
CREATE TABLE "stg_stats_gca" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "shot_creating_actions" DECIMAL(10,2),
  "shot_creating_actions_per_90" DECIMAL(10,2),
  "shot_creating_actions_live_pass" DECIMAL(10,2),
  "shot_creating_actions_dead_pass" DECIMAL(10,2),
  "shot_creating_actions_take_on" DECIMAL(10,2),
  "shot_creating_actions_shot" DECIMAL(10,2),
  "shot_creating_actions_foul_drawn" DECIMAL(10,2),
  "goal_creating_actions" DECIMAL(10,2),
  "goal_creating_actions_per_90" DECIMAL(10,2),
  "goal_creating_actions_def" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_keeper
DROP TABLE IF EXISTS "stg_stats_keeper" CASCADE;
CREATE TABLE "stg_stats_keeper" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "matches_played" INTEGER,
  "starts" INTEGER,
  "minutes" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "goals_against" DECIMAL(10,2),
  "goals_against_per_90" DECIMAL(10,2),
  "shots_on_target_against" DECIMAL(10,2),
  "saves" DECIMAL(10,2),
  "save_pct" DECIMAL(10,2),
  "wins" DECIMAL(10,2),
  "draws" DECIMAL(10,2),
  "losses" DECIMAL(10,2),
  "clean_sheets" DECIMAL(10,2),
  "clean_sheet_pct" DECIMAL(10,2),
  "penalty_attempts" INTEGER,
  "penalty_goals_against" DECIMAL(10,2),
  "penalty_saves" DECIMAL(10,2),
  "penalty_missed" DECIMAL(10,2),
  "MP" DECIMAL(10,2),
  "Starts" DECIMAL(10,2),
  "Min" DECIMAL(10,2),
  "penalty_kicks_allowed" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_keeper_adv
DROP TABLE IF EXISTS "stg_stats_keeper_adv" CASCADE;
CREATE TABLE "stg_stats_keeper_adv" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "goals_against" DECIMAL(10,2),
  "penalty_kicks_allowed" DECIMAL(10,2),
  "free_kick_goals_against" DECIMAL(10,2),
  "corner_kick_goals_against" DECIMAL(10,2),
  "own_goals_against" DECIMAL(10,2),
  "post_shot_expected_goals" DECIMAL(10,2),
  "post_shot_expected_goals_per_shot" DECIMAL(10,2),
  "post_shot_expected_goals_plus_minus" DECIMAL(10,2),
  "post_shot_expected_goals_plus_minus_per_90" DECIMAL(10,2),
  "launches" DECIMAL(10,2),
  "launch_pct" DECIMAL(10,2),
  "avg_launch_distance" DECIMAL(10,2),
  "goal_kicks" DECIMAL(10,2),
  "crosses_faced" DECIMAL(10,2),
  "crosses_stopped" DECIMAL(10,2),
  "cross_stop_pct" DECIMAL(10,2),
  "defensive_actions_outside_penalty_area" DECIMAL(10,2),
  "defensive_actions_outside_penalty_area_per_90" DECIMAL(10,2),
  "avg_distance_defensive_actions" DECIMAL(10,2),
  "opponent_penalty_area_entries_stopped" DECIMAL(10,2),
  "keeper_stops" DECIMAL(10,2),
  "keeper_stop_pct" DECIMAL(10,2),
  "keeper_opa" DECIMAL(10,2),
  "keeper_opa_per_90" DECIMAL(10,2),
  "keeper_avg_distance" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_misc
DROP TABLE IF EXISTS "stg_stats_misc" CASCADE;
CREATE TABLE "stg_stats_misc" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "yellow_cards" INTEGER,
  "red_cards" INTEGER,
  "second_yellow" DECIMAL(10,2),
  "fouls" DECIMAL(10,2),
  "fouled" DECIMAL(10,2),
  "offsides" DECIMAL(10,2),
  "crosses" DECIMAL(10,2),
  "interceptions" DECIMAL(10,2),
  "tackles_won" DECIMAL(10,2),
  "penalties_won" DECIMAL(10,2),
  "penalties_conceded" DECIMAL(10,2),
  "own_goals" DECIMAL(10,2),
  "ball_recoveries" DECIMAL(10,2),
  "aerials_won" DECIMAL(10,2),
  "aerials_lost" DECIMAL(10,2),
  "aerial_win_pct" DECIMAL(10,2),
  "shot_creating_actions_foul_drawn" DECIMAL(10,2),
  "passes_offsides" DECIMAL(10,2),
  "passes_crosses" DECIMAL(10,2),
  "own_goals_against" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_passing
DROP TABLE IF EXISTS "stg_stats_passing" CASCADE;
CREATE TABLE "stg_stats_passing" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "passes_completed" DECIMAL(10,2),
  "passes_attempted" DECIMAL(10,2),
  "pass_completion_pct" DECIMAL(10,2),
  "total_distance" DECIMAL(10,2),
  "progressive_distance" DECIMAL(10,2),
  "assists" DECIMAL(10,2),
  "expected_assists" DECIMAL(10,2),
  "expected_assists_minus_xag" DECIMAL(10,2),
  "key_passes" DECIMAL(10,2),
  "passes_into_final_third" DECIMAL(10,2),
  "passes_into_penalty_area" DECIMAL(10,2),
  "crosses_into_penalty_area" DECIMAL(10,2),
  "progressive_passes" DECIMAL(10,2),
  "expected_assists_xa" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_passing_types
DROP TABLE IF EXISTS "stg_stats_passing_types" CASCADE;
CREATE TABLE "stg_stats_passing_types" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "passes_attempted" DECIMAL(10,2),
  "passes_live" DECIMAL(10,2),
  "passes_dead" DECIMAL(10,2),
  "passes_free_kick" DECIMAL(10,2),
  "passes_through_ball" DECIMAL(10,2),
  "passes_switched" DECIMAL(10,2),
  "passes_crosses" DECIMAL(10,2),
  "passes_throw_in" DECIMAL(10,2),
  "passes_corner_kick" DECIMAL(10,2),
  "passes_in" DECIMAL(10,2),
  "passes_out" DECIMAL(10,2),
  "passes_straight" DECIMAL(10,2),
  "passes_completed" DECIMAL(10,2),
  "passes_offsides" DECIMAL(10,2),
  "passes_blocks" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_playing_time
DROP TABLE IF EXISTS "stg_stats_playing_time" CASCADE;
CREATE TABLE "stg_stats_playing_time" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "matches_played" INTEGER,
  "minutes" INTEGER,
  "minutes_per_match" DECIMAL(10,2),
  "minutes_pct" DECIMAL(10,2),
  "nineties_played" DECIMAL(10,2),
  "starts" INTEGER,
  "minutes_per_start" DECIMAL(10,2),
  "complete_matches" DECIMAL(10,2),
  "substitutions" DECIMAL(10,2),
  "minutes_per_sub" DECIMAL(10,2),
  "unused_sub" DECIMAL(10,2),
  "points_per_match" DECIMAL(10,2),
  "on_goals" DECIMAL(10,2),
  "on_goals_against" DECIMAL(10,2),
  "plus_minus" DECIMAL(10,2),
  "plus_minus_per_90" DECIMAL(10,2),
  "on_off" DECIMAL(10,2),
  "on_expected_goals" DECIMAL(10,2),
  "on_expected_goals_against" DECIMAL(10,2),
  "expected_goals_plus_minus" DECIMAL(10,2),
  "expected_goals_plus_minus_per_90" DECIMAL(10,2),
  "MP" DECIMAL(10,2),
  "Min" DECIMAL(10,2),
  "Starts" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_possession
DROP TABLE IF EXISTS "stg_stats_possession" CASCADE;
CREATE TABLE "stg_stats_possession" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "touches" DECIMAL(10,2),
  "touches_def_pen" DECIMAL(10,2),
  "touches_def_third" DECIMAL(10,2),
  "touches_mid_third" DECIMAL(10,2),
  "touches_att_third" DECIMAL(10,2),
  "touches_att_pen" DECIMAL(10,2),
  "touches_live" DECIMAL(10,2),
  "tackle_attempts" DECIMAL(10,2),
  "tackles_successful" DECIMAL(10,2),
  "tackle_success_pct" DECIMAL(10,2),
  "tackles_defeated" DECIMAL(10,2),
  "tackles_defeated_pct" DECIMAL(10,2),
  "carries" DECIMAL(10,2),
  "carry_distance" DECIMAL(10,2),
  "carry_progressive_distance" DECIMAL(10,2),
  "progressive_carries" DECIMAL(10,2),
  "carries_into_final_third" DECIMAL(10,2),
  "carries_into_penalty_area" DECIMAL(10,2),
  "miscontrols" DECIMAL(10,2),
  "dispossessed" DECIMAL(10,2),
  "receptions" DECIMAL(10,2),
  "progressive_receives" DECIMAL(10,2),
  "passes_live" DECIMAL(10,2),
  "passes_attempted" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_shooting
DROP TABLE IF EXISTS "stg_stats_shooting" CASCADE;
CREATE TABLE "stg_stats_shooting" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "goals" DECIMAL(10,2),
  "shots" DECIMAL(10,2),
  "shots_on_target" DECIMAL(10,2),
  "shots_on_target_pct" DECIMAL(10,2),
  "shots_per_90" DECIMAL(10,2),
  "shots_on_target_per_90" DECIMAL(10,2),
  "goals_per_shot" DECIMAL(10,2),
  "goals_per_shot_on_target" DECIMAL(10,2),
  "avg_distance" DECIMAL(10,2),
  "free_kicks" DECIMAL(10,2),
  "penalty_goals" INTEGER,
  "penalty_attempts" INTEGER,
  "expected_goals" DECIMAL(10,2),
  "non_penalty_xg" DECIMAL(10,2),
  "npxg_per_shot" DECIMAL(10,2),
  "goals_minus_xg" DECIMAL(10,2),
  "non_penalty_goals_minus_xg" DECIMAL(10,2),
  "shot_creating_actions_shot" DECIMAL(10,2),
  "passes_free_kick" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

-- DDL for table: stats_standard
DROP TABLE IF EXISTS "stg_stats_standard" CASCADE;
CREATE TABLE "stg_stats_standard" (
  "rank" INTEGER,
  "player_name" VARCHAR(255),
  "nation" VARCHAR(255),
  "position" VARCHAR(255),
  "squad" VARCHAR(255),
  "competition" VARCHAR(255),
  "age" INTEGER,
  "birth_year" INTEGER,
  "matches_played" INTEGER,
  "starts" INTEGER,
  "minutes" INTEGER,
  "nineties_played" DECIMAL(10,2),
  "goals" DECIMAL(10,2),
  "assists" DECIMAL(10,2),
  "goals_assists" DECIMAL(10,2),
  "goals_minus_pk" DECIMAL(10,2),
  "penalty_goals" INTEGER,
  "penalty_attempts" INTEGER,
  "yellow_cards" INTEGER,
  "red_cards" INTEGER,
  "expected_goals" DECIMAL(10,2),
  "non_penalty_xg" DECIMAL(10,2),
  "expected_assists" DECIMAL(10,2),
  "npxg_plus_xag" DECIMAL(10,2),
  "progressive_carries" DECIMAL(10,2),
  "progressive_passes" DECIMAL(10,2),
  "progressive_receives" DECIMAL(10,2),
  "goals_assists_minus_pk" DECIMAL(10,2),
  "xg_plus_xag" DECIMAL(10,2),
  "MP" DECIMAL(10,2),
  "Starts" DECIMAL(10,2),
  "Min" DECIMAL(10,2),
  "season" VARCHAR(50),
  "table_type" VARCHAR(50),
  "processed_at" TIMESTAMP
);

